### ISSUE TITLE
I am facing this error when in run "python3 MOT_Metrics.py ./vlc/gt.sqlite ./vlc/out.sqlite bboverlap 0.3". May i know what the problem could possibly be?

### ISSUE THREAD

**Issue by Unravl13** [beaupreda/clear_mot_metrics#1]
Traceback (most recent call last):
  File "MOT_Metrics.py", line 553, in <module>
    main()
  File "MOT_Metrics.py", line 540, in main
    motp, mota = mot_metrics.compute_metrics(data_annotations.min_frame, data_annotations.max_frame, ratio, method)
  File "MOT_Metrics.py", line 423, in compute_metrics
    pairings = munk.compute(costs.copy())
  File "/home/cse/.local/lib/python3.7/site-packages/munkres.py", line 427, in compute
    self.original_width = len(cost_matrix[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by beaupreda** [comment]
Sorry for the extremely late reply, but I did not see a notification for your issue at the time.

I made corrections this morning to what I think your problem is. Probably, your costs matrix had a 0 x 0 shape, because there was no annotations and hypotheses for a given frame. This has been fixed, so it should be ok now!
